# Generated by Django 5.0.6 on 2025-05-24 10:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='python', max_length=32)),
                ('code', models.TextField()),
                ('options_json', models.JSONField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('timeout', 'Timeout'), ('rate_limited', 'Rate limited')], default='ok', max_length=20)),
                ('response_text', models.TextField(blank=True, default='')),
                ('complexity_time', models.CharField(blank=True, default='', max_length=32)),
                ('complexity_space', models.CharField(blank=True, default='', max_length=32)),
                ('complexity_reasoning', models.TextField(blank=True, default='')),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='api.llmmodel')),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api.snippet')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.run')),
            ],
        ),
    ]
